### ISSUE TITLE
[Feature] Support Query-filters for `/api/search`

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#106]
**Is your feature request related to a problem? Please describe.**
We should support [google dorking](https://en.wikipedia.org/wiki/Google_hacking) style querry parameters/filters.

**Describe the solution you'd like**

Examples:

- [x] `"hs1"` search for exactly this string
- [ ] `+hs1` force this string being in the result
- [ ] `-hs1` filter this string not being in the result
- [ ] `@garching` filters for campus=garching
- [ ] `in:mi` filters, that the room/.. is contained in the `mi` 

**Describe alternatives you've considered**
Not implementing this. This is not a high priority issue.

**Additional context**
There already is partial support in some parts for some of these issues. This part does however require a lot more work.

**Comment by octycs** [comment]
Point three (negative keyword search with `-mi`) is under consideration in MeiliSearch ([see their roadmap](https://roadmap.meilisearch.com/c/104-negative-keyword-search)), but won't be there soon. So we'd need to implement that manually.

Quoted search should be there already I think.

**Comment by CommanderStorm** [comment]
See the testcases added in #104 for why this is written down ;)
It is actually not supported, at least for the testcases I added..

**Comment by CommanderStorm** [comment]
Actually, any changes can probably be merged pretty “eazy-ish”
Anything search is just basically merged in this file: https://github.com/TUM-Dev/navigatum/blob/25ba18c19de000d2a32958b2d1af0792fe8a518a/webclient/src/components/AppSearchBar.vue
and some components are here: https://github.com/TUM-Dev/navigatum/blob/25ba18c19de000d2a32958b2d1af0792fe8a518a/webclient/src/modules/autocomplete.ts

The migration does mostly code-merges, moves and minor refactoring (despite how it looks)
