### ISSUE TITLE
[Bug] Footer not at the bottom

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#113]
**Describe the bug**
Our footer does not stick to the bottom

**To Reproduce**
1. Go to any page on 'nav.tum.sexy'

**Expected behavior**
The footer should behave like a normal footer:
- stick to the bottom if content is less than the viewports height
- stick to the bottom (i.e. be out of view), if there is more content than the viewports height

**Screenshots** (I have changed the color, to make this issue more obvious)
![image](https://user-images.githubusercontent.com/26258709/168380934-a345ced4-2b2e-4cbe-9022-ce53df0c36eb.png)

**Extra context:**
- to fix this the following workflow is probably best: go to https://nav.tum.sexy and resolve the issue using the css editor of Firefox / other tools
- Insert the fix [here](https://github.com/TUM-Dev/navigatum/blob/main/webclient/src/main.scss) (using an PR)

**Comment by Marius1501** [comment]
The footer is at the bottom. Or do I misunderstand the bug @CommanderStorm ? 😄

**Comment by CommanderStorm** [comment]
No, this issue is still valid:
![image](https://user-images.githubusercontent.com/26258709/200902834-07148694-30ed-40f2-a258-246628cb70dd.png)

This issue is most prevalent on “weird” screen sizes, on some mobile devices and using some zoom levels.
If I mess with the zoom, I can fairly easily reproduce this.
