### ISSUE TITLE
[Feature] Investigate better highlighting

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#114]
**Is your feature request related to a problem? Please describe.**
As discussed in #109 meilisearch v 0.27.0 added the ability to controll highlights. We should investigate, if the issues @octycs noticed are still present.

**Describe the solution you'd like**
Investigate, wether meilisearch has fixed these two issues:
1. I found that MeiliSearch's highlighting was slow when search queries are short (such as `mi`), sometimes even doubling response times. Maybe that is resolved now, I've not tested since.
2. MeiliSearch's highlighting was typo tolerant, which I found confusing, especially when using numeric values in a search (e.g. searching for `1234` would also highlight results that contain `1334`. Additionally there was a bug that would only highlight `Garchin` when the query was `garching`, omitting the last character)

**Describe alternatives you've considered**
For short responses we could switch to our own highlighter and for other ones we could use theirs, which could solve the performace problem **(Assuming this is still an issue)**.

**Additional context**
See [changelog](https://github.com/meilisearch/MeiliSearch/releases) or the [blog](https://blog.meilisearch.com/whats-new-in-v0-27/) for more details.

Looking in the Mini-Dashboard, both of these seem to be solved.

**Comment by octycs** [comment]
There is one more thing we need to keep in mind if we used MeiliSearch's highlighting: Sometimes we reformat the result to better match the search query format (the `parsed_id`), which should also be highlighted.
