### ISSUE TITLE
[Bug] Crash because of Roomfinder Maps data for Z10

### ISSUE THREAD

**Issue by octycs** [TUM-Dev/navigatum#122]
**Describe the bug**
Z10 (and potentially other entries) have an error in the Roomfinder Maps data.

**To Reproduce**
1. Go to [https://nav.tum.sexy/building/0510](https://nav.tum.sexy/building/0510)
2. Get an empty page because of the error:
    `TypeError: view_data.maps.roomfinder.available[state.map.roomfinder.selected_index] is undefined`

**Expected behavior**
Should not crash

**Additional context**
This is a crash in the frontend (which shouldn't happen), but probably related to an error in the data.

**Comment by CommanderStorm** [comment]
Preliminary triage results:

This is a data issue. `map.roomfinder.default` is not in `map.roomfinder.availiable`

I will continue after a sort break

**Comment by CommanderStorm** [comment]
The issue was in `external/buildins_roomfinder.json`:
```json
{
  "maps": [
    ["200000", 54, "M\u00fcnchen", 640, 603],
    ["400000", 156, "M\u00fcnchen und Umgebung", 420, 515],
    ["100000000", 9, "Weltkarte Norden", 1619, 396]
  ],
 "default_map": ["4000", 12, "Stammgel\u00e4nde Basiskarte", 501, 484]
}
```

FYI: `0510` is the only building, for which this happens.

**Comment by CommanderStorm** [comment]
I had some old version of the website in my cache.

**Comment by CommanderStorm** [comment]
> I had some old version of the website in my cache.

No, Frank this is wrong.
This subsite is apparently a bit flaky..
This does not work.. again.. 

Thanks @joschahenningsen for the report ❤️

**Comment by CommanderStorm** [comment]
Apperantly we dont clean the maps default, if no maps are available:
```json
"maps": {
        "roomfinder": {
            "available": [],
            "default": "rf12"
        },
        "default": "interactive"
    },
```

@octycs what would be the expected case if no maps are available for an eintity:
```json
"maps": {
        "roomfinder": {
            "available": [],
            "default": null
        },
        "default": "interactive"
    },
```
or
```json
"maps": {
        "default": "interactive"
    },
```

**Comment by octycs** [comment]
I think the latter is better. This is what the webclient currently expects as well (https://github.com/TUM-Dev/navigatum/blob/main/webclient/src/views/view/view-view.js#L155)
