### ISSUE TITLE
[Feature] merged main campus overlay

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#139]
**Is your feature request related to a problem? Please describe.**
Currently, the maps for the main campus only show one "building". In reality, the whole main campus is one gigantic building.
This means, that maps like 
![image](https://user-images.githubusercontent.com/26258709/173083293-88f0fc2b-e5b7-4447-98c9-3b69904a04db.png)
could be more usefull for finding rooms

**Describe the solution you'd like** 
We should reflect this in our maps. 

**Describe alternatives you've considered**
Leaving them disconected is one option, but imo not a great one. The architecture is weird for this building, so some special cases will have to be handled differently probably.

**Additional context**
Currently a nice to have and not a huge priority

**Comment by Marius1501** [comment]
For this issue only the "_data/sources/46_overlay-maps.yaml_"-file is important, isn't it? How can I change this file and **test** it then? @CommanderStorm

**Comment by CommanderStorm** [comment]
Closed in favor of #403
