### ISSUE TITLE
[Feature] Bigger Map (Fullscreen-Button)

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#140]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be nice to have a larger map (especially on desktop).
![image](https://user-images.githubusercontent.com/26258709/173084287-a4ec3315-7e75-4bd6-baf3-73470b5fbb68.png)

**Describe the solution you'd like**
I think, a fullscreen-button would be a great addition.
Only adding such a button on desktop is something we should discuss

**Describe alternatives you've considered**
Making the map on desktop take a bit more room might be a good solution too

**Additional context**

**Comment by octycs** [comment]
Solved by #142
