### ISSUE TITLE
Room 5101.EG.250 has wrong location in map

### ISSUE THREAD

**Issue by jowi-tum** [TUM-Dev/NavigaTUM#1589]
**Describe the bug**
The Dean's office of the NAT in the Physics building is shown in the wrong location. 

It is shown in the lecture hall 

https://nav.tum.de/room/5101.EG.250#18/48.267221/11.675895

but in fact it is between the neighboring rooms 

https://nav.tum.de/room/5101.EG.248
https://nav.tum.de/room/5101.EG.252

**Comment by CommanderStorm** [comment]
I have updated the coordinate.

In case you are not aware, we can update all other fields as well:
- Room-name?
- Room-usage
- image
- url (see https://nav.tum.de/building/studitum-garching)
- or comment

Currently, this is sadly automated, but integrating comments is possible ^^
