### ISSUE TITLE
Make icons ("sprites") colored 

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#1637]
**Is your feature request related to a problem? Please describe.**
Currently, the icons are only partially colored
![image](https://github.com/user-attachments/assets/da6fd62c-f714-40bd-bd0f-fbb9cd6761b3)

**Describe the solution you'd like**
Since https://github.com/maplibre/martin/pull/1492 was merged, we have the ability to color our sprites.
I have already colored the "most important" (transit, parking, food-stuff) icons, but there is still a lot of work left to do.

What is missing concretely:
- add a style for `poi_activity` containing the 
- move the "lower priority"-icons (hotels, shops, ...) to a brown icon layer `po_`
- look at the console if any icons are missing / wrongly defined
- remove the legacy/black icons

**Additional context**
- how to edit the style is documented here https://github.com/TUM-Dev/NavigaTUM/tree/main/map#edit-the-style
- The specification for the kinds of POIs that exist [can be found here](https://openmaptiles.org/schema/), but there are some subtle difference between the actual data and the spec (f.ex. railway vs rail) and some additional data points. 
  Depending what needs to be styled, this might be possible or not.
- Inspiration might be the way [OSM Liberty](https://github.com/maputnik/osm-liberty) styles the icons, but with more granular styling for different zoom levels. Their spritemap is found here: https://github.com/maputnik/osm-liberty/blob/gh-pages/sprites/osm-liberty%402x.png

> [!TIP]
> Use the inspect view at the top of the map and look what data exists ^^

**Comment by CommanderStorm** [comment]
@BaumBanane Before we forget this (and because it would be very pretty/ and was as a lot of work):
Could you link the work you/we did on the coding night regarding poi-styling? ^^

**Comment by RisGar** [comment]
Ich hätte einem commit fertig, nur habe ich noch nicht herausgefunden wie das Styling getestet werden kann, da die docker compose Datei sich die Daten von nav.tum.de zieht.

**Comment by CommanderStorm** [comment]
"Testing" vom karten-stil im style-editor passt total. 😅
Das muss man nicht verkomplizieren..
