### ISSUE TITLE
[Feature] Swagger-UI instead of the Swagger Editor

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#173]
**Is your feature request related to a problem? Please describe.**
Currently our API Docs work, by just redirecting to the swagger editor. While convenient for Developing, I think there is a better solution: We could integrate swaggerui directly into navigaum.

**Describe the solution you'd like**
Something like this:

<details>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="NavigaTUMs API Documentation"
    />,
    <title>SwaggerUI</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui.css" />
  </head>
  <body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-bundle.js" crossorigin></script>
  <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-standalone-preset.js" crossorigin></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: 'https://raw.githubusercontent.com/TUM-Dev/navigatum/main/openapi.yaml',
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          //SwaggerUIStandalonePreset
        ],
        //layout: "StandaloneLayout",
      });
    };
  </script>
  </body>
</html>
```

</details>

**Describe alternatives you've considered**
Keeping our Docs as is.

**Additional context**
Current Documentation is not bad, but I would like to know what you @octycs think about this proposal, before adding the required components in a PR

**Comment by octycs** [comment]
This wouldn't exclude each other, right? I mean we could leave the edit link in the repo description but place the Swagger-UI more prominently at the top and in NavigaTUM.
