### ISSUE TITLE
[Bug] Theme/Language caching issue on direct room links

### ISSUE THREAD

**Issue by xsrf** [TUM-Dev/navigatum#186]
**Describe the bug**
Theme and language settings seem to be cached with the url and thus are not applied consistently.

**To Reproduce**
1. Open https://nav.tum.sexy/room/2906.05.013
2. Open https://nav.tum.sexy/room/2906.05.015 and change the theme
3. Open https://nav.tum.sexy/room/2906.05.013 again, the old theme is used
4. Open https://nav.tum.sexy/room/2906.05.015 again, the new theme is used

**Expected behavior**
When I switch the theme I want it everywhere, also on rooms I've already looked at in the past. Same applies for language selection.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 104.0.5112.81

**Additional context**
This is relevant if you link to rooms directly from 3rd party sites.

**Comment by CommanderStorm** [comment]
Should be fixed by https://github.com/TUM-Dev/navigatum/commit/212f64d3f0367603c14d77d6b0d9bb7738cb6030

**Comment by CommanderStorm** [comment]
Thanks for the bug report ❤️
