### ISSUE TITLE
Firefox esr is not supported [Bug] 

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/NavigaTUM#213]
**Describe the bug**
My os comes with the latest version of firefox esr (91.13.0esr) which was released in august: https://www.mozilla.org/en-US/firefox/91.13.0/releasenotes/ apparently the next esr release will be a 102.x upgrade but I suppose it might take a while to land. 
With this version I get the error `ReferenceError: structuredClone is not defined` when opening navigatum. Presumably because the browser doesn't support some feature you use.

**To Reproduce**

1. Use Firefox 91.13.0esr
2. Open any room in navigatum

**Expected behavior**
The page should be displayed as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/44805696/192398713-f4e361b1-d247-4ab3-a9ba-3c0d9f8ab20c.png)

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 11 (bullseye)
- Browser: firefox
- Version: 91.13.0esr (64-bit)

**Comment by joschahenningsen** [comment]
I just checked my updates after opening this issue. Turns out, 102.3.0esr is available now. :smile: :facepalm:  

Feel free to close this if you want, with the latest esr release it should not be too relevant anymore.

**Comment by CommanderStorm** [comment]
This will be fixed once the migration to Vue3 is complete (#200)
In the mean time I have no idea, why https://github.com/TUM-Dev/navigatum/blob/2f470660a6e27d6c9a7a9af6f6cfd9054364c520/webclient/src/core.js#L77 does not bloody work.
core is definitively included here https://github.com/TUM-Dev/navigatum/blob/2f470660a6e27d6c9a7a9af6f6cfd9054364c520/webclient/src/index.html#L53

@octycs any ideas?

**Comment by CommanderStorm** [comment]
Is `defer` the culprit?

**Comment by octycs** [comment]
> @octycs any ideas?

I can also just guess ... maybe it has to do with the function declaration being in an `if` clause (see https://stackoverflow.com/a/10069457)? Then maybe `window.structuredClone = function() { ... }` would work.
