### ISSUE TITLE
[Feature] Include room schedules

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/NavigaTUM#216]
**Is your feature request related to a problem? Please describe.**
The roomfinder made by the department of physics includes a calendar with the schedule for a room which I find quite useful: https://www.ph.tum.de/about/visit/roomfinder/?room=5510.02.001&language=de

**Describe the solution you'd like**
Perhaps we could add a similar feature to NavigaTUM.

**Describe alternatives you've considered**
Look up the schedule on tumonline. Maybe add a link to e.g. https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/wbKalender.wbRessource?$ctx=design=ca2;header=max;lang=de&pResNr=12543 ?

**Comment by CommanderStorm** [comment]
I am not convinced that this schedule is useful for **most** people (I agree that for lecturers this is essential).
⇒ This should be a lazy-loaded subcomponent and not something that is shown always as in the physics roomfinder.
Do you agree with this assessment? If not, how do you use this feature?

**Comment by joschahenningsen** [comment]
Completely agree. I need to view room schedules quite frequently to plan livestreams. Having to find the right link in tumonline is always a hassle. So linking there would already be very useful.

**Comment by octycs** [comment]
Creating a link to TUMonline should be relatively easy, because the relevant URL section is given by `entry["tumonline_data"]["calendar"]` (https://github.com/TUM-Dev/NavigaTUM/blob/main/data/data_format_geo-entry.yaml#L226):

```python
if entry["tumonline_data"]["calendar"] is not None:
    url = f"https://campus.tum.de/tumonline/{entry['tumonline_data']['calendar']}"
```

Like all the raw TUMonline data it is at the moment stripped on export.
