### ISSUE TITLE
[Feature] Introduce Ctrl + k to focus Search bar

### ISSUE THREAD

**Issue by 0ql** [TUM-Dev/NavigaTUM#248]
At any point where the search bar is visible on the page pressing `ctrl + k` focuses the search bar so you can start typing the search query instantly.

Something like this:
```javascript
window.addEventListener("keydown", (e) => {
    if (e.ctrlKey && e.key === "k") {
       e.preventDefault();
       document.getElementById("search").focus();
    }
})
```

Maybe pressing `ctrl + k` again could unfocus the search bar but that really isn't that important.

**Comment by CommanderStorm** [comment]
I would argue, that we should not override the browsers default shortcuts, but use `s` or `/` like GitHub/...
But this is a minor thing.
I think it would be best to queue this after #200

**Comment by 0ql** [comment]
Yeah, makes sense. Or maybe if you just start typing it would auto focus the search. If there are no other key binds, that could be even more convenient.

**Comment by 0ql** [comment]
Closing due to https://github.com/TUM-Dev/NavigaTUM/pull/270
