### ISSUE TITLE
[Bug] OK Button not Working for Feedback

### ISSUE THREAD

**Issue by COM8** [TUM-Dev/NavigaTUM#350]
**Describe the bug**
Clicking the "OK" button after submitting feedback has no function.
Clicking outside the dialog closes it.

**To Reproduce**

1. Submit feedback
2. On the "Thank you!" screen/dialog click "OK"
3. OK won't work

**Expected behavior**
OK should close the dialog.

**Screenshots**
![ok_navigatum](https://user-images.githubusercontent.com/11741404/211632607-74bbae8c-6c53-48ca-904f-311352884830.gif)

**Desktop (please complete the following information):**

- OS: W11
- Browser: Firefox
- Version: 108.0.2 (64-bit)

**Comment by CommanderStorm** [comment]
Thank you for the bug report <3
