### ISSUE TITLE
[Feature] [Entry] Fachschaft BUV/BGU

### ISSUE THREAD

**Issue by Aevyz** [TUM-Dev/NavigaTUM#352]
https://nav.tum.de/room/0101.02.157 sollte die BUV sein

https://www.fs.bgu.tum.de/de/kontakt#Raum

Das die TUM denkt, dass das ein CIP Pool ist, ist eine andere Sache...

**Comment by CommanderStorm** [comment]
I have renamed you as you call yourself on your website and changed the type to "Office" (which is probably more correct)
If you think this is incorrect, dont hesitate to reply to this issue

**Comment by CommanderStorm** [comment]
(just a heads-up: open the website in an inkognito tab, as this field is cached for some time)

**Comment by Aevyz** [comment]
> I have renamed you as you call yourself on your website and changed the type to "Office" (which is probably more correct) If you think this is incorrect, dont hesitate to reply to this issue

Could it be, that the Search is still broken? Looking for [0101.02.157](https://nav.tum.de/search?q=0101.02.157) still results in the CIP being listed

**Comment by CommanderStorm** [comment]
Good catch,
What I did not think about in #345 is that the search API also manages state.
Decoupling API-Data also means, that Search-Data has to be handled this way.

I have poked it and the symptoms (!= root cause) should be gone.
