### ISSUE TITLE
[Bug] duplicate maps

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#37]
**Describe the bug**
Some maps are included twice.
![image](https://user-images.githubusercontent.com/26258709/152875762-b1cf0acf-64b3-4b36-bc75-fc334a9fc465.png)
an example for this is
https://github.com/TUM-Dev/navigatum/blob/main/data/external/maps/roomfinder/171.gif
and https://github.com/TUM-Dev/navigatum/blob/main/data/external/maps/roomfinder/170.gif

**To Reproduce**
1. Go to `https://roomapi.tum.sexy/site/mri`
2. Click on 'Lagepläne'
4. See multiple `1:500000, Münchner Süden` selections, which look virtually identical

**Expected behavior**
No duplicate Maps

**Screenshots**
![image](https://user-images.githubusercontent.com/26258709/152876099-0e9110b9-10fe-4c62-8992-1b3bd4da5587.png)

**Comment by CommanderStorm** [comment]
I have lloked into this:
There are actually content duplications (1 image used mutliple times).

We can detect them like this:
```py
import glob

content_to_filename_dict = {}
file_renaming_table: dict[str, str] = dict()
for filename in glob.glob("*"):
    with open(filename, "rb") as file:
        content = file.read()
        if content in content_to_filename_dict:
            file_renaming_table[filename] = content_to_filename_dict[content]
        else:
            content_to_filename_dict[content] = filename
```

What do you think about indisceminatly renaming to the first occurance of said image?

The duplicate groups I found are:

```
22.webp,  21.webp,  20.webp 
169.webp, 170.webp, 171.webp, 167.webp
87.webp,  86.webp 
```

In maps_roomfinder.json this is:
```json
{"id": 22, "scale": "1200", "desc": "Thierschbau 7. OG", "width": 386, "height": 298, "latlonbox": {"north": "48.1488534693", "east": "11.5673200711", "west": "11.5655599404", "south": "48.1479510623", "rotation": "-22.9999992847"}},
{"id": 20, "scale": "1200", "desc": "Thierschbau 5. OG", "width": 386, "height": 298, "latlonbox": {"north": "48.1488534693", "east": "11.5673200711", "west": "11.5655599404", "south": "48.1479510623", "rotation": "-22.9999992847"}},
{"id": 21, "scale": "1200", "desc": "Thierschbau 6. OG", "width": 386, "height": 298, "latlonbox": {"north": "48.1488534693", "east": "11.5673200711", "west": "11.5655599404", "south": "48.1479510623", "rotation": "-22.9999992847"}},
```

**Comment by CommanderStorm** [comment]
I think I found a TODO, which is relevant to this:
https://github.com/TUM-Dev/navigatum/blob/6cc3ac3c21d1aa826b248f759ad8b7d98c361a83/data/processors/maps.py#L174
What do you mean by `sort`?

**Comment by octycs** [comment]
> What do you mean by `sort`?

Very likely sorting by scale
