### ISSUE TITLE
Data requests

### ISSUE THREAD

**Issue by octycs** [TUM-Dev/NavigaTUM#397]
This is a proposed tracking issue for specific data requests. Please comment if you have ideas of how to improve.

## Coordinates
Based on calendar events in a reference week from the 16-20 Jan 2023, the following (subset of) rooms have events happening in them but no coordinate known:

### Stammgelände
- [ ] [0305.02.520](https://nav.tum.de/room/0305.02.520) (5 events)
- [ ] [0206.02.202](https://nav.tum.de/room/0206.02.202) (4 events)
- [ ] [0204.04.403](https://nav.tum.de/room/0204.04.403) (4 events)
- [ ] [0502.03.250](https://nav.tum.de/room/0502.03.250) (2 events)
- [ ] [0509.02.998](https://nav.tum.de/room/0509.02.998) (2 events)
- [ ] [0104.02.407B](https://nav.tum.de/room/0104.02.407B) (2 events)
- [ ] [0305.04.523](https://nav.tum.de/room/0305.04.523) (2 events)
- [ ] [0401.03.311](https://nav.tum.de/room/0401.03.311) (1 events)

### RiWa 1 (HfP, Governance)
(Has neither maps nor coordinates at the moment)
- [ ] [2911.01.103](https://nav.tum.de/room/2911.01.103) (25 events)
- [ ] [2911.02.204](https://nav.tum.de/room/2911.02.204) (25 events)
- [ ] [2911.02.200](https://nav.tum.de/room/2911.02.200) (24 events)
- [ ] [2911.01.100](https://nav.tum.de/room/2911.01.100) (21 events)
- [ ] [2910.EG.003](https://nav.tum.de/room/2910.EG.003) (19 events)
- [ ] [2911.02.203](https://nav.tum.de/room/2911.02.203) (19 events)
- [ ] [2910.EG.004](https://nav.tum.de/room/2910.EG.004) (18 events)
- [ ] [2910.02.206](https://nav.tum.de/room/2910.02.206) (14 events)
- [ ] [2910.01.103](https://nav.tum.de/room/2910.01.103) (12 events)
- [ ] [2910.EG.001](https://nav.tum.de/room/2910.EG.001) (9 events)
- [ ] [2910.01.158](https://nav.tum.de/room/2910.01.158) (7 events)
- [ ] [2910.02.262](https://nav.tum.de/room/2910.02.262) (6 events)
- [ ] [2910.04.414](https://nav.tum.de/room/2910.04.414) (6 events)
- [ ] [2910.01.162](https://nav.tum.de/room/2910.01.162) (5 events)
- [ ] [2910.03.351](https://nav.tum.de/room/2910.03.351) (4 events)
- [ ] [2910.01.160](https://nav.tum.de/room/2910.01.160) (2 events)
- [ ] [2910.04.456](https://nav.tum.de/room/2910.04.456) (1 events)
- [ ] [2911.03.308](https://nav.tum.de/room/2911.03.308) (1 events)

### Weihenstephan
- [ ] [4214.EG.030](https://nav.tum.de/room/4214.EG.030) (21 events)
- [ ] [4277.EG.128](https://nav.tum.de/room/4277.EG.128) (18 events)
- [x] [4214.EG.010](https://nav.tum.de/room/4214.EG.010) (17 events)
- [ ] [4102.01.040](https://nav.tum.de/room/4102.01.040) (17 events)
- [x] [4214.EG.020](https://nav.tum.de/room/4214.EG.020) (16 events)
- [ ] [4277.EG.129](https://nav.tum.de/room/4277.EG.129) (16 events)
- [ ] [4217.EG.041](https://nav.tum.de/room/4217.EG.041) (16 events)
- [ ] [4124.U1.104](https://nav.tum.de/room/4124.U1.104) (15 events)
- [ ] [4317.03.305](https://nav.tum.de/room/4317.03.305) (14 events)
- [ ] [4101.01.129](https://nav.tum.de/room/4101.01.129) (14 events)
- [ ] [4219.U1.001](https://nav.tum.de/room/4219.U1.001) (14 events)
- [ ] [4102.EG.034](https://nav.tum.de/room/4102.EG.034) (14 events)
- [ ] [4277.EG.109](https://nav.tum.de/room/4277.EG.109) (14 events)
- [ ] [4308.EG.112](https://nav.tum.de/room/4308.EG.112) (13 events)
- [ ] [4102.01.038](https://nav.tum.de/room/4102.01.038) (13 events)
- [ ] [4214.U1.034](https://nav.tum.de/room/4214.U1.034) (12 events)
- [ ] [4308.EG.114](https://nav.tum.de/room/4308.EG.114) (12 events)
- [ ] [4277.EG.130](https://nav.tum.de/room/4277.EG.130) (12 events)
- [ ] [4224.02.298](https://nav.tum.de/room/4224.02.298) (12 events)
- [ ] [4113.01.105](https://nav.tum.de/room/4113.01.105) (12 events)
- [ ] [4277.EG.073B](https://nav.tum.de/room/4277.EG.073B) (11 events)
- [ ] [4215.U1.058](https://nav.tum.de/room/4215.U1.058) (11 events)
- [ ] [4214.EG.040](https://nav.tum.de/room/4214.EG.040) (9 events)
- [ ] [4277.EG.108](https://nav.tum.de/room/4277.EG.108) (9 events)
- [ ] [4215.U1.026](https://nav.tum.de/room/4215.U1.026) (9 events)
- [ ] [4153.EG.001](https://nav.tum.de/room/4153.EG.001) (9 events)
- [ ] [4213.EG.302](https://nav.tum.de/room/4213.EG.302) (8 events)
- [ ] [4219.01.020](https://nav.tum.de/room/4219.01.020) (8 events)
- [ ] [4219.U1.003](https://nav.tum.de/room/4219.U1.003) (8 events)
- [ ] [4224.02.234](https://nav.tum.de/room/4224.02.234) (8 events)
- [ ] [4214.EG.041](https://nav.tum.de/room/4214.EG.041) (7 events)
- [ ] [4102.01.043](https://nav.tum.de/room/4102.01.043) (6 events)
- [ ] [4277.EG.083](https://nav.tum.de/room/4277.EG.083) (6 events)
- [ ] [4215.EG.040](https://nav.tum.de/room/4215.EG.040) (6 events)
- [ ] [4215.EG.041](https://nav.tum.de/room/4215.EG.041) (6 events)
- [ ] [4234.EG.526](https://nav.tum.de/room/4234.EG.526) (6 events)
- [ ] [4213.EG.310](https://nav.tum.de/room/4213.EG.310) (5 events)
- [ ] [4109.EG.050](https://nav.tum.de/room/4109.EG.050) (5 events)
- [ ] [4108.EG.106](https://nav.tum.de/room/4108.EG.106) (5 events)
- [ ] [4277.EG.073A](https://nav.tum.de/room/4277.EG.073A) (5 events)
- [ ] [4220.EG.112](https://nav.tum.de/room/4220.EG.112) (5 events)
- [ ] [4220.02.101](https://nav.tum.de/room/4220.02.101) (5 events)
- [ ] [4215.EG.039](https://nav.tum.de/room/4215.EG.039) (5 events)
- [ ] [4215.U1.026A](https://nav.tum.de/room/4215.U1.026A) (5 events)
- [ ] [4217.01.114](https://nav.tum.de/room/4217.01.114) (5 events)

(<4 truncated)

### Garching (Chemie)
- [x] [5406.01.641A](https://nav.tum.de/room/5406.01.641A) (23 events)
- [x] [5403.04.330A](https://nav.tum.de/room/5403.04.330A) (21 events)
- [x] [5406.01.641K](https://nav.tum.de/room/5406.01.641K) (16 events)
- [x] [5403.04.330F](https://nav.tum.de/room/5403.04.330F) (16 events)
- [x] [5402.EG.240J](https://nav.tum.de/room/5402.EG.240J) (10 events)
- [x] [5406.02.622K](https://nav.tum.de/room/5406.02.622K) (7 events)
- [ ] [5407.01.760E](https://nav.tum.de/room/5407.01.760E) (5 events)
- [x] [5406.01.650E](https://nav.tum.de/room/5406.01.650E) (4 events)
- [x] [5407.02.710E](https://nav.tum.de/room/5407.02.710E) (2 events)
- [x] [5406.03.630F](https://nav.tum.de/room/5406.03.630F) (2 events)
- [x] [5406.01.650A](https://nav.tum.de/room/5406.01.650A) (2 events)
- [x] [5403.05.340A](https://nav.tum.de/room/5403.05.340A) (2 events)
- [x] [5406.04.630F](https://nav.tum.de/room/5406.04.630F) (1 events)
- [x] [5406.EG.630G](https://nav.tum.de/room/5406.EG.630G) (1 events)

### Garching (MW)
- [ ] [5507.01.701](https://nav.tum.de/room/5507.01.701) (16 events)
- [ ] [5502.03.237](https://nav.tum.de/room/5502.03.237) (14 events)
- [ ] [5504.03.414](https://nav.tum.de/room/5504.03.414) (13 events)
- [ ] [5506.01.638](https://nav.tum.de/room/5506.01.638) (13 events)
- [ ] [5506.EG.690H](https://nav.tum.de/room/5506.EG.690H) (10 events)
- [ ] [5501.02.142](https://nav.tum.de/room/5501.02.142) (10 events)
- [ ] [5507.03.707](https://nav.tum.de/room/5507.03.707) (8 events)
- [ ] [5504.01.401](https://nav.tum.de/room/5504.01.401) (7 events)
- [ ] [5501.02.104](https://nav.tum.de/room/5501.02.104) (6 events)
- [ ] [5505.02.537](https://nav.tum.de/room/5505.02.537) (6 events)
- [ ] [5504.02.412](https://nav.tum.de/room/5504.02.412) (4 events)
- [ ] [5504.01.442](https://nav.tum.de/room/5504.01.442) (4 events)
- [ ] [5504.02.452](https://nav.tum.de/room/5504.02.452) (4 events)
- [ ] [5503.03.340](https://nav.tum.de/room/5503.03.340) (4 events)
- [ ] [5505.U1.550](https://nav.tum.de/room/5505.U1.550) (4 events)
- [ ] [5503.01.301](https://nav.tum.de/room/5503.01.301) (3 events)
- [ ] [5501.EG.199A](https://nav.tum.de/room/5501.EG.199A) (3 events)
- [ ] [5501.U1.150](https://nav.tum.de/room/5501.U1.150) (3 events)
- [ ] [5505.03.502](https://nav.tum.de/room/5505.03.502) (3 events)
- [ ] [5515.EG.005](https://nav.tum.de/room/5515.EG.005) (3 events)
- [ ] [5504.03.408](https://nav.tum.de/room/5504.03.408) (2 events)
- [ ] [5504.01.404M](https://nav.tum.de/room/5504.01.404M) (2 events)
- [ ] [5510.U1.050](https://nav.tum.de/room/5510.U1.050) (2 events)
- [x] [5506.03.643](https://nav.tum.de/room/5506.03.643) (2 events)
- [ ] [5502.01.264](https://nav.tum.de/room/5502.01.264) (2 events)
- [ ] [5501.01.126](https://nav.tum.de/room/5501.01.126) (2 events)
- [ ] [5501.02.101](https://nav.tum.de/room/5501.02.101) (2 events)
- [ ] [5505.03.533](https://nav.tum.de/room/5505.03.533) (2 events)
- [ ] [5504.U1.450](https://nav.tum.de/room/5504.U1.450) (1 events)
- [ ] [5504.02.407](https://nav.tum.de/room/5504.02.407) (1 events)
- [ ] [5506.02.636](https://nav.tum.de/room/5506.02.636) (1 events)
- [ ] [5506.02.613B](https://nav.tum.de/room/5506.02.613B) (1 events)
- [ ] [5506.EG.699A](https://nav.tum.de/room/5506.EG.699A) (1 events)
- [ ] [5502.01.237](https://nav.tum.de/room/5502.01.237) (1 events)
- [ ] [5505.02.501](https://nav.tum.de/room/5505.02.501) (1 events)
- [ ] [5505.01.501](https://nav.tum.de/room/5505.01.501) (1 events)

### Garching (Rest)
- [ ] [5901.EG.051](https://nav.tum.de/room/5901.EG.051) (22 events)
- [ ] [5140.01.201](https://nav.tum.de/room/5140.01.201) (18 events)
- [ ] [5140.01.202](https://nav.tum.de/room/5140.01.202) (18 events)
- [ ] [5415.EG.006A](https://nav.tum.de/room/5415.EG.006A) (17 events)
- [ ] [5901.01.032](https://nav.tum.de/room/5901.01.032) (13 events)
- [ ] [5901.02.021](https://nav.tum.de/room/5901.02.021) (12 events)
- [ ] [5901.03.013](https://nav.tum.de/room/5901.03.013) (10 events)
- [ ] [5901.01.013](https://nav.tum.de/room/5901.01.013) (10 events)
- [ ] [5112.EG.101S](https://nav.tum.de/room/5112.EG.101S) (10 events)
- [ ] [5701.EG.026](https://nav.tum.de/room/5701.EG.026) (9 events)
- [ ] [5414.EG.002](https://nav.tum.de/room/5414.EG.002) (9 events)
- [ ] [5410.02.002](https://nav.tum.de/room/5410.02.002) (9 events)
- [ ] [5415.EG.006B](https://nav.tum.de/room/5415.EG.006B) (9 events)
- [ ] [5901.03.022](https://nav.tum.de/room/5901.03.022) (7 events)
- [ ] [5701.01.211](https://nav.tum.de/room/5701.01.211) (6 events)
- [ ] [5111.01.116](https://nav.tum.de/room/5111.01.116) (6 events)
- [ ] [5901.02.049](https://nav.tum.de/room/5901.02.049) (5 events)
- [ ] [5204.01.005](https://nav.tum.de/room/5204.01.005) (5 events)
- [ ] [5901.01.035](https://nav.tum.de/room/5901.01.035) (4 events)
- [ ] [5433.EG.004](https://nav.tum.de/room/5433.EG.004) (4 events)
- [ ] [5115.02.003](https://nav.tum.de/room/5115.02.003) (4 events)
- [ ] [5901.02.013](https://nav.tum.de/room/5901.02.013) (3 events)
- [ ] [5212.02.202](https://nav.tum.de/room/5212.02.202) (3 events)
- [ ] [5530.01.102](https://nav.tum.de/room/5530.01.102) (3 events)
- [ ] [5530.01.101](https://nav.tum.de/room/5530.01.101) (3 events)
- [ ] [5530.EG.003](https://nav.tum.de/room/5530.EG.003) (3 events)
- [ ] [5433.02.001](https://nav.tum.de/room/5433.02.001) (3 events)
- [ ] [5701.01.222](https://nav.tum.de/room/5701.01.222) (2 events)
- [ ] [5901.02.052](https://nav.tum.de/room/5901.02.052) (2 events)
- [ ] [5612.02.020](https://nav.tum.de/room/5612.02.020) (2 events)
- [ ] [5415.EG.003](https://nav.tum.de/room/5415.EG.003) (2 events)
- [ ] [5532.03.302](https://nav.tum.de/room/5532.03.302) (2 events)
- [ ] [5532.U1.020](https://nav.tum.de/room/5532.U1.020) (2 events)
- [ ] [5901.03.049](https://nav.tum.de/room/5901.03.049) (1 events)
- [ ] [5901.03.052](https://nav.tum.de/room/5901.03.052) (1 events)
- [ ] [5901.01.016](https://nav.tum.de/room/5901.01.016) (1 events)
- [ ] [5608.03.022](https://nav.tum.de/room/5608.03.022) (1 events)
- [ ] [5410.03.046](https://nav.tum.de/room/5410.03.046) (1 events)
- [ ] [5410.01.105](https://nav.tum.de/room/5410.01.105) (1 events)
- [ ] [5112.03.402S](https://nav.tum.de/room/5112.03.402S) (1 events)

**Comment by octycs** [comment]
I was curious why `5612.02.020` has so many event; apparently IRIS [adds any usage into the calendar](https://campus.tum.de/tumonline/tvKalender.wSicht?cOrg=14178&cRes=26772&cReadonly=J). Anyway it is probably easy to add this coordinate (given [5612.02.018](https://nav.tum.de/room/5612.02.018) and [5612.02.019](https://nav.tum.de/room/5612.02.019) or you might be close occasionally).

**Comment by CommanderStorm** [comment]
Closing as I don't think without https://github.com/TUM-Dev/NavigaTUM/pull/670 this issue makes a how lot of sense. (plus I don't think it has had any effect ^^)
