### ISSUE TITLE
[Feature] Automatic regular TUMonline updates

### ISSUE THREAD

**Issue by octycs** [TUM-Dev/NavigaTUM#424]
**Is your feature request related to a problem? Please describe.**
TUMonline seems to be updated quite a lot (more than I thought) and rooms appear to change more often than every semester.
To keep our data up to date, we should automate our TUMonline updates

**Describe the solution you'd like**
The best idea I have so far is to use GitHub actions [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) feature to update e.g. weekly our TUMonline base data by creating a PR.

**Describe alternatives you've considered**
The above is just an idea, open for discussion.

**Additional context**
Instead of the tedious current scraper, it would make sense to switch to the TUMonline XML API that we have been provided (with a token).

Belongs somewhat to #197

**Comment by CommanderStorm** [comment]
Resolved by https://github.com/TUM-Dev/NavigaTUM/pull/1114
