### ISSUE TITLE
[Feature] Serverside rendering of meta tags

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/navigatum#45]
**Is your feature request related to a problem? Please describe.**
Currently our project is rendered fully clientside. This is a problem, as for example twitterbot does not execute js and thus a hydration of the meta tags with dynamic content is not possible.

**Describe the solution you'd like**
I would like to have serverside rendering of meta tags

**Describe alternatives you've considered**
Sticking with the static tags implemented in https://github.com/TUM-Dev/navigatum/pull/43

**Comment by CommanderStorm** [comment]
search enginge bots may be an issue as well, but this is to be tested.

**Comment by octycs** [comment]
I found [this (Rendertron)](https://github.com/GoogleChrome/rendertron), which we could use when Nginx detects requests from social bots, or some search engines. Google at least [is said to support](https://codelabs.developers.google.com/codelabs/making-a-single-page-app-search-friendly/#3) metadata updated by JS after pageload.
