### ISSUE TITLE
[Feature] Advanced SEO

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/NavigaTUM#46]
**Is your feature request related to a problem? Please describe.**  
 We should include more Shema.org data:
- [ ] [Schema.org Place Microdata](https://schema.org/Place)
- [ ] [google sitelinks-searchbox](https://developers.google.com/search/docs/advanced/structured-data/sitelinks-searchbox)

Including this data may increase our conversion rate, as google may show more features. If adding the Place mikrodata would have any effekt is unclear

- [x] Add a sitemap

**Comment by octycs** [comment]
Sitemap added in #98, c.f. also #91
