### ISSUE TITLE
Thumbnails laden nicht [Bug] 

### ISSUE THREAD

**Issue by N0W0RK** [TUM-Dev/NavigaTUM#668]
**Describe the bug**
Beim Laden beliebiger Gebäudegruppen werden die Thumbnails nicht gefunden(404)

**To Reproduce**

1. Go to 'https://nav.tum.de/campus/garching' (o.ä.)

**Expected behavior**
Ein Foto des Gebäudes als Thumbnail neben dem Gebäudenamen.

**Screenshots**
![image](https://github.com/TUM-Dev/NavigaTUM/assets/22464684/a94361dc-64ba-4c64-bc7d-b0fe34b3b56b)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 114.0.1

**Comment by CommanderStorm** [comment]
Thank you for this bug report ❤️
