### ISSUE TITLE
Selecting a room from a building overview breaks room selector table [Bug] 

### ISSUE THREAD

**Issue by N0W0RK** [TUM-Dev/NavigaTUM#818]
**Describe the bug**
Selecting a room from the room selector table in a building overview breaks the room selector table.

**To Reproduce**

1. Go to any building overview.(e.g. https://nav.tum.de/building/0510)
2. Select a room from the table below the map.
3. Try to select another category.

**Expected behavior**
The catehory is switched to the one selected.

**Screenshots**
![grafik](https://github.com/TUM-Dev/NavigaTUM/assets/22464684/c588ee90-3453-448d-9e55-ea4939f2e50c)

**Desktop (please complete the following information):**

- OS: Windows 11 Home [22H2 22621.2283]
- Firefox
- 117.0.1

**Comment by CommanderStorm** [comment]
To be honest, I have tried debugging this in the past, but I have no idea why vue suddenly enters a broken state.
My assumption is that somewhere I am using vue wrong, but I can't figure out where.

**Comment by CommanderStorm** [comment]
Resolved in the v1.5 release a few months ago
