### ISSUE TITLE
[Feature] Add links to OSM / Google Maps

### ISSUE THREAD

**Issue by octycs** [TUM-Dev/navigatum#87]
**Is your feature request related to a problem? Please describe.**
Except copying the address, there is currently no way to use an external service to navigate to the displayed building / site.
(See also #86)

**Describe the solution you'd like**
Add a small link to OSM / Google Maps on the Info Card, based on the entries coordinates.

**Describe alternatives you've considered**
/

**Additional context**
Tasks could include:
- Add relevant HTML/CSS in `webclient/src/views/view/view-view.inc|.scss`. The data is already there, and every entry is guaranteed to have coordinate data.

**Comment by CommanderStorm** [comment]
I think this can be generalised:
A share button would probably be nice.
This should include a way to toggle if you share a google maps/osm/navigatum link.

Note that there is already some link copy code for this feature:
![image](https://user-images.githubusercontent.com/26258709/169603287-63d2a7a2-ee3f-44c1-890c-0d36c1cc66cd.png)

**Comment by octycs** [comment]
Closed by #136
