### ISSUE TITLE
[Bug] Falsche Raumzuordnung 0509.Z1.921

### ISSUE THREAD

**Issue by manulen** [TUM-Dev/NavigaTUM#872]
Das gleiche Problem wie in #862 besteht auch für Raum [0509.Z1.921](https://nav.tum.de/view/0509.Z1.921)
Die richtige Beschreibung findet man beim Raum [0509.01.921](https://nav.tum.de/view/0509.01.921)

Vielen Dank!

**Comment by Strice91** [comment]
Currently, there are about 20 people a day in the wrong building. We would be very happy if this is updated. Thank you!

**Comment by CommanderStorm** [comment]
@manulen Thanks for reporting this issue, patch will be deployed in ~4m (± caching time of the browser)
