### ISSUE TITLE
[Bug] Title Image width wrong

### ISSUE THREAD

**Issue by Bentipa** [TUM-Dev/NavigaTUM#898]
**Describe the bug**
Detail Page Info Image width is wrong.

**To Reproduce**

1. Go to [any building page](https://nav.tum.de/building/mw)

**Expected behavior**
Image should have container width (100%).

**Screenshots**
![image](https://github.com/TUM-Dev/NavigaTUM/assets/11789478/95531ac8-5b8f-4b75-88d6-d1da94870424)

**Additional context**
It seems like the image has classes "max-w-full w-full" assigned but they are not specified via CSS, which seems to be the issue.

**Comment by CommanderStorm** [comment]
Thanks for reporting. For some reason tailwind was not getting loaded.
=> fixed now
