### ISSUE TITLE
[Bug] Missalignment of Icons in Room View

### ISSUE THREAD

**Issue by braupach** [TUM-Dev/NavigaTUM#986]
**Describe the bug**
Calendar Icon is misaligned with other icons.

**To Reproduce**

1. Go to a Room with a Calendar in TUM-Online
2. See missaligned Icons

**Expected behavior**
Icons being aligned

**Screenshots**
![grafik](https://github.com/TUM-Dev/NavigaTUM/assets/28948901/f60eb8e1-8eea-480b-822c-210472d80d61)

**Desktop (please complete the following information):**

- OS: Linux (Manjaro)
- DE: Gnome
- Browser: Firefox Browser
- Version: 121.0.1 (64-Bit)

**Smartphone (please complete the following information):**

- Device: Pocophone F1
- OS: LineageOS (Android 13)
- Browser: Firefox
- Version: 122.0.1

**Additional context**
This might be a Problem because of diffrent alignment Values and methods for the diffrent Elements.
Following Alignments were Taken from the Firefox Website Analyzer:
Calendar: Margin Bottom -2px
Link: Margin Top +4px
Flag: vertical-align -10%

It seems like the source of the Problem is not the size of the Icons as they all seem to be 14x14

**Comment by CommanderStorm** [comment]
This will be one of the bugs fixed by the new frontend coming in #911
This still needs some polishing (f.ex. the darkmode and the search bar) before being review+mergable.
